2016-07-12 01:30:15,562 [mswblmppy]  DEBUG    svc do run....
2016-07-12 01:36:41,578 [mswblmppy]  DEBUG    svc do run....
2016-07-12 01:39:50,421 [mswblmppy]  DEBUG    svc do run....
2016-07-12 01:40:38,780 [mswblmppy]  DEBUG    svc do run....
2016-07-12 02:25:27,328 [mswblmppy]  DEBUG    svc do run....
2016-07-12 02:32:59,453 [mswblmppy]  ERROR    Traceback (most recent call last):
  File "U:\new_mswblm\new_mswblm\bprocess\playSound.py", line 207, in playCash
    conn = win32com.client.Dispatch(r'ADODB.Connection')
  File "U:\Python27\lib\site-packages\win32com\client\__init__.py", line 95, in Dispatch
    dispatch, userName = dynamic._GetGoodDispatchAndUserName(dispatch,userName,clsctx)
  File "U:\Python27\lib\site-packages\win32com\client\dynamic.py", line 114, in _GetGoodDispatchAndUserName
    return (_GetGoodDispatch(IDispatch, clsctx), userName)
  File "U:\Python27\lib\site-packages\win32com\client\dynamic.py", line 91, in _GetGoodDispatch
    IDispatch = pythoncom.CoCreateInstance(IDispatch, None, clsctx, pythoncom.IID_IDispatch)
com_error: (-2147221008, '\xc9\xd0\xce\xb4\xb5\xf7\xd3\xc3 CoInitialize\xa1\xa3', None, None)

2016-07-12 02:33:45,671 [mswblmppy]  DEBUG    svc do run....
2016-07-12 02:34:26,328 [mswblmppy]  DEBUG    svc do run....
2016-07-12 02:37:53,578 [mswblmppy]  DEBUG    svc do run....
2016-07-12 02:42:22,905 [mswblmppy]  DEBUG    svc do run....
2016-07-12 02:43:49,733 [mswblmppy]  DEBUG    svc do run....
2016-07-12 02:44:00,046 [mswblmppy]  ERROR    Traceback (most recent call last):
  File "U:\new_mswblm\new_mswblm\bprocess\playSound.py", line 207, in playCash
    conn = win32com.client.Dispatch(r'ADODB.Connection')
  File "U:\Python27\lib\site-packages\win32com\client\__init__.py", line 95, in Dispatch
    dispatch, userName = dynamic._GetGoodDispatchAndUserName(dispatch,userName,clsctx)
  File "U:\Python27\lib\site-packages\win32com\client\dynamic.py", line 114, in _GetGoodDispatchAndUserName
    return (_GetGoodDispatch(IDispatch, clsctx), userName)
  File "U:\Python27\lib\site-packages\win32com\client\dynamic.py", line 91, in _GetGoodDispatch
    IDispatch = pythoncom.CoCreateInstance(IDispatch, None, clsctx, pythoncom.IID_IDispatch)
com_error: (-2147221008, '\xc9\xd0\xce\xb4\xb5\xf7\xd3\xc3 CoInitialize\xa1\xa3', None, None)

2016-07-12 02:45:29,594 [mswblmppy]  DEBUG    svc do run....
2016-07-12 02:47:37,875 [mswblmppy]  DEBUG    svc do run....
2016-07-12 02:53:42,875 [mswblmppy]  DEBUG    svc do run....
2016-07-12 03:22:18,469 [mswblmppy]  DEBUG    svc do run....
2016-07-12 03:24:37,421 [mswblmppy]  DEBUG    svc do run....
2016-07-12 22:16:06,183 [mswblmppy]  DEBUG    svc do run....
